apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  selector:
    app: devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
  type: NodePort
